apiVersion: v1
data: 
  SERVER_PROFILE_PATH: serverProfile/pingdataproxy
  SERVER_PROFILE_URL: https://github.com/lmc-inc/directorypoc.git
  USER_BASE_DN: "dc=example,dc=com"
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: likeminds
    app.kubernetes.io/name: pingdirectoryproxy
  name: likeminds-pingdirectoryproxy-env-vars