apiVersion: v1
data:
  PF_DELEGATOR_CLIENTID: "dadmin"
  PD_DELEGATOR_PROFILE_SCOPE_ENABLED: "true"
  PD_ENGINE_PUBLIC_HOSTNAME: "dataproxy.likemindsdemo.com"
  PD_ENGINE_PUBLIC_PORT: "1443"
  PD_DELEGATOR_HTTPS_PORT: "1443"
  HTTPS_PORT: "1443"
  SERVER_PROFILE_PATH: serverProfile/pingdelegator
  SERVER_PROFILE_URL: https://github.com/lmc-inc/directorypoc.git
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: likeminds
    app.kubernetes.io/name: pingdelegator
  name: likeminds-pingdelegator-env-vars