kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
- ping-directory
- ping-dataconsole
- ping-datasync
- ping-directory-proxy
- ping-delegator
- pingfederate
- global-env.yaml